### ISSUE TITLE
server is unresponsive error.

### ISSUE THREAD

**Issue by covid19-code** [sskorol/alexa-smart-home-skill-template#8]
Thanks for the Skill Template, it is very well structured and easy to get started. 

I have recently used it, but getting one problem.

But now I'm having new problem, whenever I try to give "On" or "Off" command from the app UI it shows "server is unresponsive", and when I give voice command I got following response "I'm not quite sure what went wrong"

But in the both the cases Command gets executed successfully and My device gets turn on or off as per request, and same status is being updated in Alexa app as well in few sec.

I also checked and calculated response time it's within 1 sec for my server. So I'm not sure what is wrong with it.

Could you please help me.

**Comment by sskorol** [comment]
Could you please provide a screenshot, which UI are you using for sending commands?

But in general, I can assume some changes in Alexa API. So most likely it's required to update existing interfaces in code.

I'm not using Alexa skills for now, as mostly researching offline speech recognition alternatives. Unfortunately, I can't say for sure what went wrong.

However, I can probably check it on one of the further weekends. The main problem is time, as I'll need to raise the entire IoT + middleware infrastructure first. So it might be time-consuming.

**Comment by covid19-code** [comment]
Thanks for reply, 

Here's the screenshot 
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/62683432/91561782-c71ab980-e959-11ea-824d-6a2580bf67ed.jpg)

Can you explain How can I make [Deferred Response](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-response.html#deferred)  From Lambda, so after when execution gets completed of given command we can fire event as described in the doc.

**Comment by sskorol** [comment]
According to docs, a deferred response should be sent synchronously before the actual response.
Regarding implementation:
- Add this response type to https://github.com/sskorol/alexa-smart-home-skill-template/blob/master/src/model/HeaderName.ts first
- Add new abstract method, e.g. `isDeferrable` into https://github.com/sskorol/alexa-smart-home-skill-template/blob/master/src/core/RequestHandler.ts
- Make a default implementation which returns false into https://github.com/sskorol/alexa-smart-home-skill-template/blob/master/src/core/AbstractHandler.ts as according to docs this response type supported only by specific interfaces
- Send a new deferred response from within https://github.com/sskorol/alexa-smart-home-skill-template/blob/master/src/core/AbstractHandler.ts#L16 before returning the main response. But do it only if `isDeferrable === true`
- Create a new handler for your device type or just a child class (in case of existing handler) which will override `isDeferrable` to return true

This algo should work. But also make sure you override `isDeferrable` only for supported interfaces.

**Comment by covid19-code** [comment]
Great, thanks for all help.

But I fixed my issue, somewhere from server it was returning boolean status instead of "ON"/"OFF", that was causing the issue.
Anyway this might be helpful anyone else or future work. 

Thanks for your support.
